# Generated by Django 3.0.8 on 2021-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210506_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='is_accepted',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
