# Generated by Django 3.2 on 2021-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210505_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='geeks_field',
            field=models.BooleanField(default=False),
        ),
    ]
