# Generated by Django 3.2 on 2021-05-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210505_1801'),
        ('groups', '0002_auto_20210505_2036'),
    ]

    operations = [
    ]
