# Generated by Django 3.2 on 2021-05-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmember_geeks_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='geeks_field',
            new_name='is_accepted',
        ),
    ]
