# Generated by Django 3.2 on 2021-05-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_geeks_field_groupmember_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='is_accepted',
        ),
    ]
